name: ECS "Deploy Task Definition To Scheduled Task" Action for GitHub Actions
description: Registers an Amazon ECS task definition & deploys it to related ECS scheduled tasks
branding:
  color: orange
  icon: cloud
inputs:
  cluster:
    default: default
    description: The name of the ECS cluster hosting the scheduled task(s).
    required: false
  task-definition:
    description: The path to the ECS task definition file to register
    required: true
  rule-prefix:
    default: ''
    description: The CloudWatch Event name prefix to update
    required: false
outputs:
  task-definition-arn:
    description: The ARN of the registered ECS task definition
runs:
  using: node16
  main: dist/index.js
